package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/justinholmes/grunter/internal/config"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate GitLab CI pipeline configuration",
	Long:  "Generates a .gitlab-ci.yml file that integrates grunter into your GitLab CI/CD pipeline with progressive deployment, canary gates, and rollback support.",
	RunE:  runInit,
}

func init() {
	initCmd.Flags().StringP("output", "o", ".gitlab-ci.yml", "output file path")
	initCmd.Flags().Bool("force", false, "overwrite existing file")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	cfgPath, _ := cmd.Flags().GetString("config")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}

	outPath, _ := cmd.Flags().GetString("output")
	force, _ := cmd.Flags().GetBool("force")

	if !force {
		if _, statErr := os.Stat(outPath); statErr == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", outPath)
		}
	}

	content := generateGitLabCI(cfg, cfgPath)

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", outPath, err)
	}

	fmt.Fprintf(os.Stderr, "Generated %s\n", outPath)
	return nil
}

func generateGitLabCI(cfg *config.Config, cfgPath string) string {
	var b strings.Builder

	b.WriteString("# Generated by grunter init\n")
	b.WriteString("# Progressive deployment pipeline with per-environment planning,\n")
	b.WriteString("# canary gates, rollback, and OIDC ID tokens\n\n")

	// Only create pipelines for MR events and default branch pushes.
	// This prevents spurious pipelines on tag pushes from create-release.
	b.WriteString("workflow:\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n\n")

	// Build stage list
	b.WriteString("stages:\n")
	b.WriteString("  - detect\n")
	b.WriteString("  - plan\n")

	// Per-environment generate + rollout stages (post-merge)
	if len(cfg.Environments) >= 2 {
		for i := 1; i < len(cfg.Environments); i++ {
			env := cfg.Environments[i]
			fmt.Fprintf(&b, "  - generate-%s\n", env.Name)
			if env.IsMultiRegion() {
				fmt.Fprintf(&b, "  - approve-%s\n", env.Name)
				fmt.Fprintf(&b, "  - rollout-%s-canary\n", env.Name)
				fmt.Fprintf(&b, "  - %s-canary-gate\n", env.Name)
				fmt.Fprintf(&b, "  - rollout-%s\n", env.Name)
			} else if env.RequiresRFCCheck() || env.ApprovalGroup != "" {
				fmt.Fprintf(&b, "  - approve-%s\n", env.Name)
				fmt.Fprintf(&b, "  - rollout-%s\n", env.Name)
			} else {
				fmt.Fprintf(&b, "  - rollout-%s\n", env.Name)
			}
		}
	}
	b.WriteString("  - release\n\n")

	// Variables
	b.WriteString("variables:\n")
	fmt.Fprintf(&b, "  GRUNTER_CONFIG: %q\n", cfgPath)
	// Add ServiceNow change number variable if any environment uses ServiceNow
	for _, env := range cfg.Environments {
		if env.RFC != nil && env.RFC.Source == config.RFCSourceServiceNow && env.RFC.ChangeNumberVar != "" {
			fmt.Fprintf(&b, "  %s: \"\"  # ServiceNow change number for %s\n", env.RFC.ChangeNumberVar, env.Name)
		}
	}
	b.WriteString("\n")

	// --- MR Pipeline ---
	b.WriteString("# ============================================================\n")
	b.WriteString("# MR Pipeline: detect changes, run plans, post comments\n")
	b.WriteString("# ============================================================\n\n")

	// Detect job (MR only)
	b.WriteString("detect:\n")
	b.WriteString("  stage: detect\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
	b.WriteString("  script:\n")
	b.WriteString("    - grunter orchestrate --config \"$GRUNTER_CONFIG\" -o execution-plan.json\n")
	b.WriteString("  artifacts:\n")
	b.WriteString("    paths:\n")
	b.WriteString("      - execution-plan.json\n")
	b.WriteString("    expire_in: 1 day\n\n")

	// Plan job (MR only)
	b.WriteString("plan:\n")
	b.WriteString("  stage: plan\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
	b.WriteString("  needs:\n")
	b.WriteString("    - detect\n")
	b.WriteString("  script:\n")
	b.WriteString("    - |\n")
	b.WriteString("      for unit in $(jq -r '.layers[].units[].path' execution-plan.json); do\n")
	b.WriteString("        echo \"Planning: $unit\"\n")
	b.WriteString("        grunter execute plan \"$unit\" --config \"$GRUNTER_CONFIG\" -o \"plan-${unit//\\//-}.txt\" || true\n")
	b.WriteString("        grunter comment \\\n")
	b.WriteString("          --input \"plan-${unit//\\//-}.txt\" \\\n")
	b.WriteString("          --unit \"$unit\" \\\n")
	b.WriteString("          --action plan \\\n")
	b.WriteString("          --config \"$GRUNTER_CONFIG\" || true\n")
	b.WriteString("      done\n\n")

	// Envdiff (MR only)
	if len(cfg.Environments) >= 2 {
		b.WriteString("envdiff:\n")
		b.WriteString("  stage: plan\n")
		b.WriteString("  rules:\n")
		b.WriteString("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
		b.WriteString("  needs:\n")
		b.WriteString("    - detect\n")
		b.WriteString("  script:\n")
		first := cfg.Environments[0].Name
		last := cfg.Environments[len(cfg.Environments)-1].Name
		fmt.Fprintf(&b, "    - grunter envdiff %s %s --config \"$GRUNTER_CONFIG\" -o envdiff-report.md\n", first, last)
		b.WriteString("    - grunter comment --raw --input envdiff-report.md --unit envdiff --config \"$GRUNTER_CONFIG\"\n")
		b.WriteString("  artifacts:\n")
		b.WriteString("    paths:\n")
		b.WriteString("      - envdiff-report.md\n")
		b.WriteString("    expire_in: 1 day\n\n")
	}

	// --- Post-Merge Pipeline ---
	if len(cfg.Environments) >= 2 {
		b.WriteString("# ============================================================\n")
		b.WriteString("# Post-Merge Pipeline: progressive deployment per environment\n")
		b.WriteString("# Each environment's plan is generated after the previous one\n")
		b.WriteString("# completes, ensuring plans reflect the latest deployed state.\n")
		b.WriteString("# ============================================================\n\n")

		// For each target environment (skip the first — it's the source)
		for i := 1; i < len(cfg.Environments); i++ {
			source := cfg.Environments[i-1]
			target := cfg.Environments[i]

			// Previous stage dependency
			var needsJob string
			if i == 1 {
				needsJob = "" // first target, no dependency
			} else {
				needsJob = fmt.Sprintf("rollout-%s", cfg.Environments[i-1].Name)
			}

			generateJobName := fmt.Sprintf("generate-%s", target.Name)

			if target.IsMultiRegion() {
				writeMultiRegionEnv(&b, source, target, generateJobName, needsJob, cfgPath)
			} else {
				writeSingleRegionEnv(&b, source, target, generateJobName, needsJob, cfgPath)
			}
		}
	}

	// Release job
	b.WriteString("# Create a release after all environments are deployed\n")
	b.WriteString("create-release:\n")
	b.WriteString("  stage: release\n")
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	if len(cfg.Environments) >= 2 {
		lastEnv := cfg.Environments[len(cfg.Environments)-1]
		b.WriteString("  needs:\n")
		fmt.Fprintf(&b, "    - rollout-%s\n", lastEnv.Name)
	}
	b.WriteString("  script:\n")
	b.WriteString("    - |\n")
	b.WriteString("      curl --fail-with-body -s -X POST \\\n")
	b.WriteString("        \"${CI_SERVER_URL}/api/v4/projects/${CI_PROJECT_ID}/releases\" \\\n")
	b.WriteString("        -H \"JOB-TOKEN: ${CI_JOB_TOKEN}\" \\\n")
	b.WriteString("        -H \"Content-Type: application/json\" \\\n")
	b.WriteString("        -d \"$(jq -n \\\n")
	b.WriteString("          --arg tag \"deploy-${CI_PIPELINE_IID}\" \\\n")
	b.WriteString("          --arg name \"Deployment ${CI_PIPELINE_IID}\" \\\n")
	b.WriteString("          --arg desc \"Progressive deployment from pipeline ${CI_PIPELINE_IID}\" \\\n")
	b.WriteString("          --arg ref \"${CI_COMMIT_SHA}\" \\\n")
	b.WriteString("          '{tag_name: $tag, name: $name, description: $desc, ref: $ref}')\"\n")

	return b.String()
}

// writeSingleRegionEnv generates the generate + rollout jobs for a single-region
// (or no-region) environment. One child pipeline handles everything.
// When RFC or approval_group is configured, an approval gate is added.
func writeSingleRegionEnv(b *strings.Builder, source, target config.Environment, generateJobName, needsJob, cfgPath string) {
	artifactFile := fmt.Sprintf("%s-rollout.yml", target.Name)

	// Generate job
	fmt.Fprintf(b, "# Generate %s deployment plan (comparing %s → %s)\n", target.Name, source.Name, target.Name)
	fmt.Fprintf(b, "%s:\n", generateJobName)
	fmt.Fprintf(b, "  stage: generate-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	if needsJob != "" {
		b.WriteString("  needs:\n")
		fmt.Fprintf(b, "    - %s\n", needsJob)
	}
	b.WriteString("  script:\n")
	fmt.Fprintf(b, "    - grunter promote --from %s --to %s --pipeline -o %s --config \"$GRUNTER_CONFIG\"\n",
		source.Name, target.Name, artifactFile)
	b.WriteString("  artifacts:\n")
	b.WriteString("    paths:\n")
	fmt.Fprintf(b, "      - %s\n", artifactFile)
	b.WriteString("    expire_in: 1 day\n\n")

	// If RFC or approval group is configured, add an approval gate
	needsApproval := target.RequiresRFCCheck() || target.ApprovalGroup != ""
	rolloutNeeds := generateJobName

	if needsApproval {
		writeApproveDeployGate(b, target, generateJobName)
		rolloutNeeds = fmt.Sprintf("approve:%s-deploy", target.Name)
	}

	// Rollout trigger job
	rolloutJobName := fmt.Sprintf("rollout-%s", target.Name)
	fmt.Fprintf(b, "# Deploy to %s\n", target.Name)
	fmt.Fprintf(b, "%s:\n", rolloutJobName)
	fmt.Fprintf(b, "  stage: rollout-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", rolloutNeeds)
	if needsApproval {
		fmt.Fprintf(b, "    - job: %s\n", generateJobName)
		b.WriteString("      artifacts: true\n")
	}
	b.WriteString("  trigger:\n")
	b.WriteString("    include:\n")
	fmt.Fprintf(b, "      - artifact: %s\n", artifactFile)
	fmt.Fprintf(b, "        job: %s\n", generateJobName)
	b.WriteString("    strategy: depend\n\n")
}

// writeMultiRegionEnv generates the generate + canary rollout + canary gate +
// full rollout jobs for a multi-region environment. The canary region deploys
// first via its own child pipeline, then the canary gate (approve/rollback)
// appears as a separate stage in the parent pipeline, and finally the remaining
// regions deploy via a second child pipeline.
func writeMultiRegionEnv(b *strings.Builder, source, target config.Environment, generateJobName, needsJob, cfgPath string) {
	canaryArtifact := fmt.Sprintf("%s-canary-rollout.yml", target.Name)
	fullArtifact := fmt.Sprintf("%s-rollout.yml", target.Name)
	canaryPlanArtifact := fmt.Sprintf("%s-canary-plan.json", target.Name)

	// Generate job — produces canary pipeline, full pipeline, and canary plan JSON
	fmt.Fprintf(b, "# Generate %s deployment plans (comparing %s → %s)\n", target.Name, source.Name, target.Name)
	fmt.Fprintf(b, "%s:\n", generateJobName)
	fmt.Fprintf(b, "  stage: generate-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	if needsJob != "" {
		b.WriteString("  needs:\n")
		fmt.Fprintf(b, "    - %s\n", needsJob)
	}
	b.WriteString("  script:\n")
	fmt.Fprintf(b, "    - grunter promote --from %s --to %s --pipeline --canary -o %s --config \"$GRUNTER_CONFIG\"\n",
		source.Name, target.Name, canaryArtifact)
	fmt.Fprintf(b, "    - grunter promote --from %s --to %s --pipeline --after-canary -o %s --config \"$GRUNTER_CONFIG\"\n",
		source.Name, target.Name, fullArtifact)
	fmt.Fprintf(b, "    - grunter promote --from %s --to %s --json --canary --config \"$GRUNTER_CONFIG\" > %s\n",
		source.Name, target.Name, canaryPlanArtifact)
	b.WriteString("  artifacts:\n")
	b.WriteString("    paths:\n")
	fmt.Fprintf(b, "      - %s\n", canaryArtifact)
	fmt.Fprintf(b, "      - %s\n", fullArtifact)
	fmt.Fprintf(b, "      - %s\n", canaryPlanArtifact)
	b.WriteString("    expire_in: 1 day\n\n")

	// Approval gate — manual job with group membership check before any prod deployment
	approveDeployJob := fmt.Sprintf("approve:%s-deploy", target.Name)
	canaryRegion := target.Regions[0]
	writeApproveDeployGate(b, target, generateJobName)

	// Canary rollout (child pipeline — first region only)
	// Runs automatically after the approval gate job succeeds.
	canaryRolloutJob := fmt.Sprintf("rollout-%s-canary", target.Name)
	fmt.Fprintf(b, "# Deploy canary to %s/%s (runs after deploy approval)\n", target.Name, canaryRegion)
	fmt.Fprintf(b, "%s:\n", canaryRolloutJob)
	fmt.Fprintf(b, "  stage: rollout-%s-canary\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", approveDeployJob)
	fmt.Fprintf(b, "    - job: %s\n", generateJobName)
	b.WriteString("      artifacts: true\n")
	b.WriteString("  trigger:\n")
	b.WriteString("    include:\n")
	fmt.Fprintf(b, "      - artifact: %s\n", canaryArtifact)
	fmt.Fprintf(b, "        job: %s\n", generateJobName)
	b.WriteString("    strategy: depend\n\n")

	// Canary gate — approve and rollback in the parent pipeline
	writeParentCanaryGate(b, target, canaryRolloutJob, generateJobName, canaryPlanArtifact)

	// Full rollout — approve:canary already checked group membership,
	// but rollout-prod is also manual with group check to ensure only
	// approved group members can trigger the remaining regions too.
	approveCanaryJob := fmt.Sprintf("approve:%s-canary", target.Name)
	rolloutJobName := fmt.Sprintf("rollout-%s", target.Name)

	// Manual approval gate for full rollout (same group check)
	approveRolloutJob := fmt.Sprintf("approve:%s-rollout", target.Name)
	fmt.Fprintf(b, "# Manual gate — approve full %s rollout (remaining regions)\n", target.Name)
	fmt.Fprintf(b, "%s:\n", approveRolloutJob)
	fmt.Fprintf(b, "  stage: rollout-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("      when: manual\n")
	b.WriteString("      allow_failure: false\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", approveCanaryJob)
	if target.ApprovalGroup != "" {
		b.WriteString("  script:\n")
		b.WriteString("    - |\n")
		fmt.Fprintf(b, "      APPROVAL_GROUP=%q\n", target.ApprovalGroup)
		b.WriteString("      HTTP_CODE=$(curl -s -o /dev/null -w \"%{http_code}\" \\\n")
		b.WriteString("        \"${CI_SERVER_URL}/api/v4/groups/${APPROVAL_GROUP}/members/${GITLAB_USER_ID}\" \\\n")
		b.WriteString("        -H \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\")\n")
		b.WriteString("      if [ \"$HTTP_CODE\" != \"200\" ]; then\n")
		b.WriteString("        echo \"ERROR: ${GITLAB_USER_LOGIN} is not a member of group ${APPROVAL_GROUP}\"\n")
		b.WriteString("        exit 1\n")
		b.WriteString("      fi\n")
		fmt.Fprintf(b, "      echo \"Full %s rollout approved by ${GITLAB_USER_LOGIN}.\"\n\n", target.Name)
	} else {
		b.WriteString("  script:\n")
		fmt.Fprintf(b, "    - echo \"Full %s rollout approved.\"\n\n", target.Name)
	}

	// Rollout trigger (runs automatically after approval)
	fmt.Fprintf(b, "# Deploy remaining %s regions (runs after rollout approval)\n", target.Name)
	fmt.Fprintf(b, "%s:\n", rolloutJobName)
	fmt.Fprintf(b, "  stage: rollout-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", approveRolloutJob)
	fmt.Fprintf(b, "    - job: %s\n", generateJobName)
	b.WriteString("      artifacts: true\n")
	b.WriteString("  trigger:\n")
	b.WriteString("    include:\n")
	fmt.Fprintf(b, "      - artifact: %s\n", fullArtifact)
	fmt.Fprintf(b, "        job: %s\n", generateJobName)
	b.WriteString("    strategy: depend\n\n")
}

// writeApproveDeployGate writes a manual approval job that gates any deployment
// to the target environment. When RFC is configured, rfc-check runs first.
// When approval_group is configured, only members of that group can trigger the deployment.
func writeApproveDeployGate(b *strings.Builder, target config.Environment, generateJobName string) {
	approveDeployJob := fmt.Sprintf("approve:%s-deploy", target.Name)
	fmt.Fprintf(b, "# Manual gate — approve %s deployment\n", target.Name)
	fmt.Fprintf(b, "%s:\n", approveDeployJob)
	fmt.Fprintf(b, "  stage: approve-%s\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("      when: manual\n")
	b.WriteString("      allow_failure: false\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", generateJobName)
	writeIDTokens(b, target)
	b.WriteString("  script:\n")

	// RFC check step (before group membership check)
	if target.RequiresRFCCheck() {
		b.WriteString("    - |\n")
		b.WriteString("      # RFC and deployment window check\n")
		fmt.Fprintf(b, "      grunter rfc-check --env %s --config \"$GRUNTER_CONFIG\"\n", target.Name)
	}

	// Group membership check
	if target.ApprovalGroup != "" {
		b.WriteString("    - |\n")
		fmt.Fprintf(b, "      APPROVAL_GROUP=%q\n", target.ApprovalGroup)
		b.WriteString("      HTTP_CODE=$(curl -s -o /dev/null -w \"%{http_code}\" \\\n")
		b.WriteString("        \"${CI_SERVER_URL}/api/v4/groups/${APPROVAL_GROUP}/members/${GITLAB_USER_ID}\" \\\n")
		b.WriteString("        -H \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\")\n")
		b.WriteString("      if [ \"$HTTP_CODE\" != \"200\" ]; then\n")
		b.WriteString("        echo \"ERROR: ${GITLAB_USER_LOGIN} is not a member of group ${APPROVAL_GROUP}\"\n")
		b.WriteString("        exit 1\n")
		b.WriteString("      fi\n")
		fmt.Fprintf(b, "      echo \"%s deployment approved by ${GITLAB_USER_LOGIN}.\"\n", target.Name)
	} else if !target.RequiresRFCCheck() {
		// No RFC and no group — just a message
		fmt.Fprintf(b, "    - echo \"%s deployment approved.\"\n", target.Name)
	}

	b.WriteString("\n")
}

// writeParentCanaryGate writes approve and rollback manual jobs into the parent
// pipeline for the canary gate of a multi-region environment.
func writeParentCanaryGate(b *strings.Builder, target config.Environment, canaryRolloutJob, generateJobName, canaryPlanArtifact string) {
	canaryRegion := target.Regions[0]

	fmt.Fprintf(b, "# --- %s Canary Gate ---\n", target.Name)
	fmt.Fprintf(b, "# Approve to proceed with remaining %s regions, or rollback the canary.\n\n", target.Name)

	// Rollback job
	fmt.Fprintf(b, "rollback:%s-canary:\n", target.Name)
	fmt.Fprintf(b, "  stage: %s-canary-gate\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("      when: manual\n")
	b.WriteString("      allow_failure: true\n")
	fmt.Fprintf(b, "  environment:\n")
	fmt.Fprintf(b, "    name: %s/%s\n", target.Name, canaryRegion)
	fmt.Fprintf(b, "    action: stop\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", canaryRolloutJob)
	fmt.Fprintf(b, "    - job: %s\n", generateJobName)
	b.WriteString("      artifacts: true\n")
	b.WriteString("  script:\n")
	b.WriteString("    - echo \"Rolling back canary deployment...\"\n")
	b.WriteString("    - git fetch origin $CI_COMMIT_BEFORE_SHA\n")
	b.WriteString("    - git checkout $CI_COMMIT_BEFORE_SHA\n")
	b.WriteString("    - |\n")
	fmt.Fprintf(b, "      for unit in $(jq -r '.stages[].layers[].units[].path' %s); do\n", canaryPlanArtifact)
	b.WriteString("        grunter execute apply \"$unit\" --config \"$GRUNTER_CONFIG\"\n")
	b.WriteString("      done\n\n")

	// Approve job
	fmt.Fprintf(b, "approve:%s-canary:\n", target.Name)
	fmt.Fprintf(b, "  stage: %s-canary-gate\n", target.Name)
	b.WriteString("  rules:\n")
	b.WriteString("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH\n")
	b.WriteString("      when: manual\n")
	b.WriteString("      allow_failure: false\n")
	b.WriteString("  needs:\n")
	fmt.Fprintf(b, "    - %s\n", canaryRolloutJob)

	// Approval group restriction
	if target.ApprovalGroup != "" {
		b.WriteString("  script:\n")
		b.WriteString("    - |\n")
		fmt.Fprintf(b, "      APPROVAL_GROUP=%q\n", target.ApprovalGroup)
		b.WriteString("      HTTP_CODE=$(curl -s -o /dev/null -w \"%{http_code}\" \\\n")
		b.WriteString("        \"${CI_SERVER_URL}/api/v4/groups/${APPROVAL_GROUP}/members/${GITLAB_USER_ID}\" \\\n")
		b.WriteString("        -H \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\")\n")
		b.WriteString("      if [ \"$HTTP_CODE\" != \"200\" ]; then\n")
		b.WriteString("        echo \"ERROR: ${GITLAB_USER_LOGIN} is not a member of group ${APPROVAL_GROUP}\"\n")
		b.WriteString("        exit 1\n")
		b.WriteString("      fi\n")
		fmt.Fprintf(b, "      echo \"Canary approved by ${GITLAB_USER_LOGIN}. Deploying remaining %s regions.\"\n\n", target.Name)
	} else {
		b.WriteString("  script:\n")
		fmt.Fprintf(b, "    - echo \"Canary approved. Deploying remaining %s regions.\"\n\n", target.Name)
	}
}

// idToken pairs an env var name with an OIDC audience for GitLab CI id_tokens.
type idToken struct {
	VarName  string
	Audience string
}

// collectIDTokens returns ID token declarations needed by the environment's
// custom RFC and/or deployment window configs.
func collectIDTokens(env config.Environment) []idToken {
	var tokens []idToken
	seen := make(map[string]bool)

	if env.RFC != nil && env.RFC.AuthType == "id_token" && env.RFC.AuthTokenVar != "" {
		if !seen[env.RFC.AuthTokenVar] {
			aud := env.RFC.AuthTokenAud
			if aud == "" {
				aud = "${CI_SERVER_URL}"
			}
			tokens = append(tokens, idToken{VarName: env.RFC.AuthTokenVar, Audience: aud})
			seen[env.RFC.AuthTokenVar] = true
		}
	}

	if env.DeploymentWindow != nil && env.DeploymentWindow.AuthType == "id_token" && env.DeploymentWindow.AuthTokenVar != "" {
		if !seen[env.DeploymentWindow.AuthTokenVar] {
			aud := env.DeploymentWindow.AuthTokenAud
			if aud == "" {
				aud = "${CI_SERVER_URL}"
			}
			tokens = append(tokens, idToken{VarName: env.DeploymentWindow.AuthTokenVar, Audience: aud})
			seen[env.DeploymentWindow.AuthTokenVar] = true
		}
	}

	return tokens
}

// writeIDTokens emits the id_tokens block for a job if the environment uses
// id_token auth for its custom RFC or deployment window config.
func writeIDTokens(b *strings.Builder, env config.Environment) {
	tokens := collectIDTokens(env)
	if len(tokens) == 0 {
		return
	}

	b.WriteString("  id_tokens:\n")
	for _, t := range tokens {
		fmt.Fprintf(b, "    %s:\n", t.VarName)
		fmt.Fprintf(b, "      aud: %s\n", t.Audience)
	}
}
