package cmd

import (
	"fmt"
	"strings"

	"github.com/justinholmes/grunter/internal/config"
)

// generatePipelineYAML creates a GitLab CI child pipeline YAML from a progressive deployment plan.
// The generated pipeline includes:
// - Deploy jobs per unit with GitLab environments and OIDC ID tokens
// - Dependency ordering via needs (respecting execution layers)
// - Canary gate with rollback and approve manual jobs (when includeCanaryGate is true)
func generatePipelineYAML(plan *ProgressiveDeploymentPlan, cfg *config.Config, configPath string, includeCanaryGate bool) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by grunter promote --pipeline\n")
	b.WriteString("# Do not edit — this file is regenerated on each deployment\n\n")

	// Variables
	b.WriteString("variables:\n")
	fmt.Fprintf(&b, "  GRUNTER_CONFIG: %q\n", configPath)
	b.WriteString("  ROLLBACK_SHA: $CI_COMMIT_BEFORE_SHA\n")
	b.WriteString("\n")

	// Build stage list
	canaryIdx := -1
	type stageInfo struct {
		name     string
		stageIdx int
	}
	var stages []stageInfo

	for i, s := range plan.Stages {
		name := deployStageSlug(s)
		stages = append(stages, stageInfo{name: name, stageIdx: i})
		if s.IsCanary {
			canaryIdx = i
			if includeCanaryGate {
				stages = append(stages, stageInfo{name: "canary-gate", stageIdx: -1})
			}
		}
	}

	b.WriteString("stages:\n")
	for _, s := range stages {
		fmt.Fprintf(&b, "  - %s\n", s.name)
	}
	b.WriteString("\n")

	// Track job names from the previous layer for dependency chaining
	var prevLayerJobs []string

	for stageIdx, stage := range plan.Stages {
		slug := deployStageSlug(stage)
		afterCanary := canaryIdx >= 0 && stageIdx > canaryIdx

		// Section header
		label := fmt.Sprintf("%s %s", stage.Environment, stage.Region)
		if stage.IsCanary {
			label += " (canary)"
		}
		if afterCanary {
			label += " (post-canary)"
		}
		fmt.Fprintf(&b, "# --- %s ---\n", strings.TrimSpace(label))

		var currentLayerJobs []string

		for layerIdx, layer := range stage.Layers {
			currentLayerJobs = nil

			for _, unit := range layer.Units {
				jobName := unitJobName(unit.Path)
				currentLayerJobs = append(currentLayerJobs, jobName)

				fmt.Fprintf(&b, "%q:\n", jobName)
				fmt.Fprintf(&b, "  stage: %s\n", slug)

				// GitLab environment
				envName := gitlabEnvironmentName(unit.Path)
				fmt.Fprintf(&b, "  environment:\n")
				fmt.Fprintf(&b, "    name: %s\n", envName)

				// OIDC ID token for cloud provider authentication
				b.WriteString("  id_tokens:\n")
				b.WriteString("    GITLAB_OIDC_TOKEN:\n")
				b.WriteString("      aud: $CI_SERVER_URL\n")

				// Dependencies (needs)
				var needs []string
				if layerIdx > 0 {
					needs = prevLayerJobs
				} else if afterCanary && includeCanaryGate && layerIdx == 0 {
					needs = []string{"approve:canary"}
				} else if stageIdx > 0 && layerIdx == 0 {
					needs = prevLayerJobs
				}

				if len(needs) > 0 {
					b.WriteString("  needs:\n")
					for _, n := range needs {
						fmt.Fprintf(&b, "    - %q\n", n)
					}
				}

				// Script — inject plan+check before apply when destroy protection is enabled
				b.WriteString("  script:\n")
				env := cfg.GetEnvironment(stage.Environment)
				if env != nil && env.HasDestroyProtection() {
					fmt.Fprintf(&b, "    - grunter execute plan %q --config \"$GRUNTER_CONFIG\" -o plan-output.txt\n", unit.Path)
					fmt.Fprintf(&b, "    - grunter plan-check --env %s --input plan-output.txt --config \"$GRUNTER_CONFIG\"\n", stage.Environment)
				}
				fmt.Fprintf(&b, "    - grunter execute apply %q --config \"$GRUNTER_CONFIG\" -o apply-output.txt\n", unit.Path)
				fmt.Fprintf(&b, "    - grunter comment --input apply-output.txt --unit %q --action apply --env %q --config \"$GRUNTER_CONFIG\" || true\n", unit.Path, stage.Environment)
				b.WriteString("\n")
			}

			prevLayerJobs = currentLayerJobs
		}

		// Canary gate: rollback + approve
		if stage.IsCanary && includeCanaryGate {
			writeCanaryGate(&b, stage, prevLayerJobs)
		}
	}

	return b.String()
}

// writeCanaryGate adds rollback and approve manual jobs after the canary deployment.
func writeCanaryGate(b *strings.Builder, stage DeploymentStage, canaryJobs []string) {
	b.WriteString("# --- Canary Gate ---\n")
	b.WriteString("# Click 'rollback:canary' to revert the canary region to the pre-merge state.\n")
	b.WriteString("# Click 'approve:canary' to proceed with the full rollout.\n\n")

	// Rollback job
	fmt.Fprintf(b, "%q:\n", "rollback:canary")
	b.WriteString("  stage: canary-gate\n")
	b.WriteString("  when: manual\n")
	b.WriteString("  allow_failure: true\n")

	// GitLab environment with stop action
	envName := fmt.Sprintf("%s/%s", stage.Environment, stage.Region)
	fmt.Fprintf(b, "  environment:\n")
	fmt.Fprintf(b, "    name: %s\n", envName)
	fmt.Fprintf(b, "    action: stop\n")

	if len(canaryJobs) > 0 {
		b.WriteString("  needs:\n")
		for _, n := range canaryJobs {
			fmt.Fprintf(b, "    - %q\n", n)
		}
	}

	b.WriteString("  script:\n")
	b.WriteString("    - echo \"Rolling back canary deployment...\"\n")
	b.WriteString("    - git fetch origin $ROLLBACK_SHA\n")
	b.WriteString("    - git checkout $ROLLBACK_SHA\n")

	// Apply canary units in reverse layer order from the pre-merge repo state
	for layerIdx := len(stage.Layers) - 1; layerIdx >= 0; layerIdx-- {
		for _, unit := range stage.Layers[layerIdx].Units {
			fmt.Fprintf(b, "    - grunter execute apply %q --config \"$GRUNTER_CONFIG\"\n", unit.Path)
		}
	}
	b.WriteString("\n")

	// Approve job
	fmt.Fprintf(b, "%q:\n", "approve:canary")
	b.WriteString("  stage: canary-gate\n")
	b.WriteString("  when: manual\n")
	b.WriteString("  allow_failure: false\n")

	if len(canaryJobs) > 0 {
		b.WriteString("  needs:\n")
		for _, n := range canaryJobs {
			fmt.Fprintf(b, "    - %q\n", n)
		}
	}

	b.WriteString("  script:\n")
	b.WriteString("    - echo \"Canary approved. Proceeding with full rollout.\"\n\n")
}

// deployStageSlug creates a GitLab CI stage name from a deployment stage.
func deployStageSlug(s DeploymentStage) string {
	if s.Region != "" {
		return fmt.Sprintf("deploy-%s-%s", s.Environment, s.Region)
	}
	return "deploy-" + s.Environment
}

// unitJobName creates a GitLab CI job name from a unit path.
// e.g., "envs/prod/us-east-1/vpc" → "deploy:prod:us-east-1:vpc"
func unitJobName(unitPath string) string {
	p := strings.TrimPrefix(unitPath, "envs/")
	return "deploy:" + strings.ReplaceAll(p, "/", ":")
}

// gitlabEnvironmentName creates a GitLab environment name from a unit path.
// e.g., "envs/prod/us-east-1/vpc" → "prod/us-east-1"
func gitlabEnvironmentName(unitPath string) string {
	p := strings.TrimPrefix(unitPath, "envs/")
	parts := strings.Split(p, "/")
	if len(parts) >= 2 {
		return parts[0] + "/" + parts[1]
	}
	return parts[0]
}

// tfStateName creates a Terraform state name from a unit path.
// e.g., "envs/prod/us-east-1/vpc" → "prod-us-east-1-vpc"
func tfStateName(unitPath string) string {
	p := strings.TrimPrefix(unitPath, "envs/")
	return strings.ReplaceAll(p, "/", "-")
}

